import type { FamilyMember } from "./types"

export const initialMember: FamilyMember = {
  firstName: "",
  lastName: "",
  dateOfBirth: "",
  age: 0,
  gender: "MALE",
  relation: "",
  maritalStatus: "",
  gotra: "",
  femaleGotra: "",
  disability: false,
  bloodGroup: "",
  mobileNumber: "",
  email: "",
  isCurrentAddressInIndia: true,
  currentCountry: "भारत",
  isStudent: false,
  educationLevel: "",
  classCompleted: "",
  currentClass: "",
  collegeCourse: "",
  institutionName: "",
  enrollmentStatus: "",
  schoolName: "",
  higherEducationType: "",
  currentEducationCity: "",
  currentEducationCountry: "",
  isHelpRequiredFromSamaj: false,
  isCurrentlyEnrolled: false,
  dropoutReason: "",
  educationMode: "",
  isStudyingAbroad: false,
  scholarshipReceived: false,
  scholarshipDetails: "",
  boardOrUniversity: "",
  yearOfPassing: undefined,
  fieldOfStudy: "",
  isEmployed: false,
  isSeekingJob: false,
  occupationType: "",
  employmentStatus: "",
  monthlyIncome: 0,
  incomeSourceCountry: false,
  incomeSourceCountryName: "",
  countryName: "",
  jobCategory: "",
  employerOrganizationName: "",
  isGovernmentJob: false,
  jobPosition: "",
  jobType: "",
  workExperienceYears: 0,
  isSelfEmployed: false,
  selfEmployedJobType: "",
  nameOfBusiness: "",
  businessCategory: "",
  businessType: "",
  customBusinessType: "",
  numberOfEmployees: 0,
  sizeOfBusiness: "",
  businessRegistration: false,
  isBusinessRegistered: false,
  willingToHirePeople: false,
  needsEmployees: false,
  occupationState: "",
  occupationCity: "",
  preferredJobLocation: "",
  preferredSector: "",
  isOpenToRelocate: false,
  workingHoursPerWeek: 0,
  hasAdditionalSkills: false,
  jobSearchSector: "",
  customJobSearchSector: "",
  wantsToGoAbroad: false,
  hasPassport: false,
  livestock: "",
  landOwned: 0,
  houseType: "",
  houseOwnership: "",
  hasElectricity: false,
  waterSource: "",
  hasToilet: false,
  cookingFuel: "",
  hasHealthIssues: false,
  chronicDisease: "",
  isVaccinated: false,
  hasHealthInsurance: false,
  isInterestedInFutureHealthPolicy: false,
  hasSmartphone: false,
  hasInternet: false,
  hasBankAccount: false,
  hasJanDhan: false,
  isMukhiya: false,
  welfareSchemes: [],
  isInterestedInFutureSamuhikVivah: false,
  vehicleType: "NONE",
  personPermanentAddress: "",
  personPermanentState: "",
  personPermanentDistrict: "",
  personPermanentPincode: "",
  personPermanentVillage: "",
  personCurrentAddress: "",
  personCurrentState: "",
  personCurrentDistrict: "",
  personCurrentPincode: "",
  personCurrentVillage: "",
  isInterestedInFinancialAssistance: false,
  govBenefitInterestfromsamaj: false,
  educaionalState: "",
  educationalDistrict: "",

}

export const statesAndDistricts: Record<string, string[]> = {
  "आंध्र प्रदेश": ["अल्लूरी सीतारामा राजू", "अनाकापल्ली", "अनंतपुर", "अन्नामय्या", "बापटला", "चित्तूर", "डॉ बीआर अंबेडकर कोनासीमा", "पूर्वी गोदावरी", "एलुरु", "गुंटूर", "काकीनाडा", "कृष्णा", "कुर्नूल", "नंद्याल", "एनटीआर", "पालनाडु", "पार्वतीपुरम मान्यम", "प्रकाशम", "श्री पोट्टी श्रीरामुलु नेल्लोर", "श्री सत्य साईं", "श्रीकाकुलम", "तिरुपति", "विशाखापत्तनम", "विजयनगरम", "पश्चिम गोदावरी", "वाईएसआर"],
  "अरुणाचल प्रदेश": ["अंजॉ", "चांगलांग", "पूर्व कामेंग", "पूर्व सियांग", "कुरुंग कुमे", "लोहित", "लोंगडिंग", "निचला दिबांग घाटी", "निचला सुबनसिरी", "पापुम पारे", "तवांग", "तिरप", "ऊपरी सियांग", "ऊपरी सुबनसिरी", "ऊपरी दिबांग घाटी", "पश्चिम कामेंग", "पश्चिम सियांग", "क्र दाई", "नम्साई", "लेपा रादा", "सियांग", "कामेंग", "पक्के-केसांग", "लोअर सियांग", "लोअर सुबनसिरी", "शियमी", "पेंगांग"],
  असम: ["बक्सा", "बारपेटा", "बोंगाईगांव", "कछार", "चराईदेव", "चिरांग", "दरंग", "धेमाजी", "धुबरी", "डिब्रूगढ़", "दीमा हसाओ", "गोवालपारा", "गोलाघाट", "हैलाकांडी", "होजाई", "जोरहाट", "कामरूप", "कामरूप महानगर", "कार्बी आंगलोंग", "करीमगंज", "कोकराझार", "लखीमपुर", "माजुली", "मोरीगांव", "नगांव", "नलबाड़ी", "शिवसागर", "शोणितपुर", "दक्षिण सालमारा-मनकाचर", "तिनसुकिया", "उदलगुरी"],
  बिहार: ["अररिया", "अरवल", "औरंगाबाद", "बाँका", "बेगूसराय", "भागलपुर", "भोजपुर", "बक्सर", "दरभंगा", "पूर्वी चंपारण", "गया", "गोपालगंज", "जमुई", "जहानाबाद", "कैमू��", "कटिहार", "खगड़िया", "किशनगंज", "लखीसराय", "मधेपुरा", "मधुबनी", "मुंगेर", "मुजफ्फरपुर", "नालंदा", "नवादा", "पटना", "पूर्णिया", "रोहतास", "सहरसा", "समस्तीपुर", "सारण", "शेखपुरा", "शिवहर", "सीतामढ़ी", "सिवान", "सुपौल", "वैशाली", "पश्चिमी चंपारण"],
  छत्तीसगढ़: ["बलौदा बाज़ार", "बालोद", "बलरामपुर", "बस्तर", "बेमेतरा", "बीजापुर", "बिलासपुर", "दंतेवाड़ा", "धमतरी", "दुर्ग", "गरियाबंद", "जांजगीर-चंपा", "जशपुर", "कवर्धा", "कांकेर", "कोंडागांव", "कोरबा", "कोरिया", "महासमुंद", "मुंगेली", "नारायणपुर", "रायगढ़", "रायपुर", "राजनांदगांव", "सुकमा", "सूरजपुर", "सरगुजा", "गौरला-पेंद्रा-मरवाही", "मोहला-मानपुर-अंबागढ़ चौकी", "सारंगढ़-बिलाईगढ़", "शक्ति", "मनेन्द्रगढ़-चिरमिरी-भरतपुर", "खैरागढ़-छुईखदान-गंडई"],
  गोवा: ["उत्तरी गोवा", "दक्षिणी गोवा"],
  गुजरात: ["अहमदाबाद", "अमरेली", "आणंद", "अरावली", "बनासकांठा", "भरूच", "भावनगर", "बोटाद", "छोटा उदयपुर", "दाहोद", "डांग", "देवभूमि द्वारका", "गांधीनगर", "गिर सोमनाथ", "जामनगर", "जूनागढ़", "खेड़ा", "कच्छ", "महिसागर", "महेसाणा", "मोरबी", "नर्मदा", "नवसारी", "पंचमहाल", "पाटन", "पोरबंदर", "राजकोट", "साबरकांठा", "सूरत", "सुरेन्द्रनगर", "तापी", "वडोदरा", "वलसाड"],
  हरियाणा: ["अंबाला", "भिवानी", "चरखी दादरी", "फरीदाबाद", "फतेहाबाद", "गुरुग्राम", "हिसार", "झज्जर", "जींद", "कैथल", "करनाल", "कुरुक्षेत्र", "महेंद्रगढ़", "नूंह", "पलवल", "पंचकुला", "पानीपत", "रेवाड़ी", "रोहतक", "सिरसा", "सोनीपत", "यमुनानगर"],
  झारखंड: ["बोकारो", "चतरा", "देवघर", "धनबाद", "दुमका", "पूर्वी सिंहभूम", "गढ़वा", "गिरिडीह", "गोड्डा", "गुमला", "हजारीबाग", "जामताड़ा", "खूंटी", "कोडरमा", "लातेहार", "लोहरदगा", "पाकुड़", "पलामू", "रामगढ़", "रांची", "साहिबगंज", "सरायकेला खरसावां", "सिमडेगा", "पश्चिमी सिंहभूम"],
  कर्नाटक: ["बागलकोट", "बल्लारी", "बेलगावी", "बेंगलुरु ग्रामीण", "बेंगलुरु शहरी", "बीदर", "चामराजनगर", "चिक्कबल्लापुर", "चिकमगलूर", "चित्रदुर्ग", "दक्षिण कन्नड़", "दावणगेरे", "धारवाड़", "गदग", "हावेरी", "हसन", "कलबुर्गी", "कोडागु", "कोलार", "कोप्पल", "मांड्या", "मैसूर", "रायचूर", "रामनगर", "शिवमोग्गा", "तुमकर", "उडुपी", "उत्तर कन्नड़", "विजयपुरा", "विजयनगर", "यादगीर"],
  केरल: ["अलेप्पी", "एर्नाकुलम", "इडुक्की", "कन्नूर", "कासरगोड", "कोल्लम", "कोट्टायम", "कोझिकोड", "मलप्पुरम", "पालक्काड", "पथनमथिट्टा", "तिरुवनंतपुरम", "त्रिशूर", "वायनाड"],
  "मध्य प्रदेश": ["अगर मालवा", "अलीराजपुर", "अनूपपुर", "अशोकनगर", "बालाघाट", "बड़वानी", "बैतूल", "भिंड", "भोपाल", "बुरहानपुर", "छतरपुर", "छिंदवाड़ा", "दमोह", "दतिया", "देवास", "धार", "डिंडोरी", "गुना", "ग्वालियर", "हरदा", "होशंगाबाद", "इंदौर", "जबलपुर", "झाबुआ", "कटनी", "खंडवा", "खरगोन", "मंडला", "मंदसौर", "मुरैना", "नरसिंहपुर", "नीमच", "पन्ना", "रायसेन", "राजगढ़", "रतलाम", "रीवा", "सागर", "सतना", "सीहोर", "सिवनी", "शहडोल", "शाजापुर", "श्योपुर", "शिवपुरी", "सीधी", "सिंगरौली", "टीकमगढ़", "उज्जैन", "उमरिया", "विदिशा", "मैहर", "पांढुर्ना", "नागदा", "मऊगंज"],
  महाराष्ट्र: ["अहमदनगर", "अकोला", "अमरावती", "औरंगाबाद", "बीड", "भंडारा", "बुलढाणा", "चंद्रपुर", "धुले", "गड़चिरोली", "गोंदिया", "हिंगोली", "जलगांव", "जालना", "कोल्हापुर", "लातूर", "मुंबई शहर", "मुंबई उपनगर", "नागपुर", "नांदेड", "नंदुरबार", "नासिक", "उस्मानाबाद", "पालघर", "परभणी", "पुणे", "रायगढ़", "रत्नागिरी", "सांगली", "सातारा", "सिंधुदुर्ग", "सोलापुर", "ठाणे", "वर्धा", "वाशिम", "यवतमाल"],
  मेघालय: ["पूर्वी गारो हिल्स", "पूर्वी जयंतिया हिल्स", "पूर्वी खासी हिल्स", "ईस्टर्न वेस्ट खासी हिल्स", "उत्तर गारो हिल्स", "री-भोई", "दक्षिण गारो हिल्स", "दक्षिण-पश्चिम गारो हिल्स", "दक्षिण-पश्चिम खासी हिल्स", "पश्चिम गारो हिल्स", "पश्चिम जयंतिया हिल्स", "पश्चिम खासी हिल्स"],
  मिजोरम: ["आइजोल", "लुंगलेई", "साईहा", "चम्फाई", "कोलासिब", "सेरछिप", "लॉन्गत्लाई", "मामित", "हनाथियाल", "सैटुअल", "खवज़वाल"],
  नगालैंड: ["चुमुकेदिमा", "दीमापुर", "किफिरे", "कोहिमा", "लोंगलेंग", "मोकोकचुंग", "मोन", "नोकलाक", "पेरेन", "फेक", "शामतोर", "तुएनसांग", "वोखा", "ज़ुन्हेबोटो", "सेइहामा", "न्यूलैंड"],
  ओडिशा: ["अनगुल", "बोलनगीर", "बालेश्वर", "बरगढ़", "भद्रक", "कटक", "देवगढ़", "ढेंकनाल", "गजपति", "गंजम", "जगतसिंहपुर", "जाजपुर", "झारसुगुड़ा", "कालाहांडी", "कंधमाल", "केन्द्रापड़ा", "केन्दुझर", "खुर्दा", "कोरापुट", "मालकानगिरि", "मयूरभंज", "नबरंगपुर", "नुआपाड़ा", "पुरी", "रायगड़ा", "संबलपुर", "सुबरनापुर", "सुंदरगढ़", "नुआपाड़ा", "जगतसिंहपुर"],
  पंजाब: ["अमृतसर", "बरनाला", "बठिंडा", "फिरोजपुर", "फरीदकोट", "फतेहगढ़ साहिब", "फाजिल्का", "गुरदासपुर", "होशियारपुर", "जालंधर", "कपूरथला", "लुधियाना", "मानसा", "मोगा", "मुक्तसर", "पठानकोट", "पटियाला", "रूपनगर", "साहिबजादा अजीत सिंह नगर", "संगरूर", "शहीद भगत सिंह नगर", "तरनतारन", "मालेरकोटला"],
  राजस्थान: ["अजमेर", "अलवर", "बांसवाड़ा", "बारां", "बाड़मेर", "बालोतरा", "भरतपुर", "भीलवाड़ा", "बीकानेर", "ब्यावर", "बूंदी", "चित्तौड़गढ़", "चूरू", "दौसा", "डीग", "धौलपुर", "डूंगरपुर", "गंगापुर सिटी", "हनुमानगढ़", "जयपुर", "जयपुर ग्रामीण", "जैसलमेर", "जालौर", "जोधपुर", "जोधपुर ग्रामीण", "झुंझुनू", "केकड़ी", "करौली", "खैरथल-तिजारा", "कोटा", "कोटपूतली-बहरोड़", "नागौर", "नीम का थाना", "फलोदी", "प्रतापगढ़", "राजसमंद", "सांचोर", "सवाई माधोपुर", "शाहपुरा", "सीकर", "सिरोही", "श्री गंगानगर", "सलूम्बर", "टोंक", "उदयपुर", "डीडवाना-कुचामन", "दूदू", "गंगापुर सिटी", "फतेहपुर", "सीकर"],
  सिक्किम: ["पूर्वी सिक्किम", "पश्चिमी सिक्किम", "उत्तरी सिक्किम", "दक्षिण सिक्किम", "पाकयोंग", "नामची"],
  तमिलनाडु: ["अरियालुर", "चेन्नई", "कोयंबटूर", "कुड्डालोर", "धर्मपुरी", "डिंडीगुल", "इरोड", "कल्लाकुरिची", "कांचीपुरम", "कन्याकुमारी", "करूर", "कृष्णागिरी", "मदुरै", "मयिलादुथुरै", "नागपट्टिनम", "नमक्कल", "नीलगिरि", "थेनी", "तिरुवन्नामलाई", "तिरुवरुर", "तिरुचिरापल्ली", "तिरुनेलवेली", "तिरुपुर", "तिरुवल्लुर", "थूथुकुडी", "वेल्लोर", "विल्लुपुरम", "विरुधुनगर", "पुदुक्कोट्टई", "रामनाथपुरम", "सेलम", "शिवगंगा", "तंजावुर", "तेनकासी", "तिरुप्पट्टूर", "तिरुचिरापल्ली", "कांचीपुरम", "मदुरै"],
  त्रिपुरा: ["धलाई", "गोमती", "खोवाई", "उत्तर त्रिपुरा", "सिपाहीजाला", "दक्षिण त्रिपुरा", "उनाकोटी", "पश्चिम त्रिपुरा"],
  उत्तराखंड: ["अल्मोड़ा", "बागेश्वर", "चमोली", "चंपावत", "देहरादून", "हरिद्वार", "नैनीताल", "पौड़ी गढ़वाल", "पिथौरागढ़", "रुद्रप्रयाग", "टिहरी गढ़वाल", "उधम सिंह नगर", "उत्तरकाशी"],
  "पश्चिम बंगाल": ["अलीपुरद्वार", "बांकुरा", "बीरभूम", "कूचबिहार", "दक्षिण दिनाजपुर", "दार्जिलिंग", "हुगली", "हावड़ा", "जलपाईगुड़ी", "झारग्राम", "कलिम्पोंग", "कोलकाता", "मालदा", "मुर्शिदाबाद", "नदिया", "उत्तर 24 परगना", "पश्चिम बर्धमान", "पश्चिम मेदिनीपुर", "पूर्वी बर्धमान", "पूर्वी मेदिनीपुर", "पुरुलिया", "दक्षिण 24 परगना", "उत्तर 24 परगना"],
}

export const occupationTypes = [
  { label: "किसान", value: "farmer" },
  { label: "मजदूर", value: "laborer" },
  { label: "निजी नौकरी", value: "private_job" },
  { label: "सरकारी नौकरी", value: "government_job" },
  { label: "स्व-रोजगार", value: "self_employed" },
  { label: "व्यापार", value: "business" },
  { label: "पेशेवर (डॉक्टर, वकील आदि)", value: "professional" },
  { label: "फ्रीलांसर", value: "freelancer" },
  { label: "स्टार्टअप संस्थापक", value: "startup_founder" },
  { label: "घरेलू सहायक / कामकाजी महिला", value: "domestic_worker" },
  { label: "गृहिणी", value: "housewife" },
  { label: "सेवानिवृत्त", value: "retired" },
  { label: "गिग वर्कर (Zomato, Uber आदि)", value: "gig_worker" },
  { label: "प्रशिक्षु / इंटर्न", value: "intern" },
  { label: "विक्रेता / दुकानदार", value: "vendor" },
  { label: "दस्तकारी / शिल्पकार", value: "artisan" },
  { label: "अन्य", value: "other" },
]

export const jobTypes = [
  { label: "इंजीनियर", value: "engineer" },
  { label: "डॉक्टर", value: "doctor" },
  { label: "मेडिकल वर्कर", value: "medical_worker" },
  { label: "आईटी प्रोफेशनल", value: "it_professional" },
  { label: "शिक्षक", value: "teacher" },
  { label: "वकील", value: "lawyer" },
  { label: "प्रशासनिक अधिकारी", value: "administrative_officer" },
  { label: "अकाउंटेंट", value: "accountant" },
  { label: "बैंकिंग", value: "banking" },
  { label: "सेल्स & मार्केटिंग", value: "sales_marketing" },
  { label: "HR", value: "hr" },
  { label: "अन्य", value: "other" },
]

export const businessTypes = [
  { label: "MSME", value: "msme" },
  { label: "प्राइवेट लिमिटेड", value: "private_ltd" },
  { label: "प्रोप्राइटरशिप", value: "proprietorship" },
  { label: "पार्टनरशिप", value: "partnership" },
  { label: "शॉप/दुकान", value: "shop" },
  { label: "ऑनलाइन बिजनेस", value: "online_business" },
  { label: "अन्य", value: "other" },
]

export const countries = [
  { label: "अफगानिस्तान", value: "Afghanistan" },
  { label: "अल्बानिया", value: "Albania" },
  { label: "अल्जीरिया", value: "Algeria" },
  { label: "अंडोरा", value: "Andorra" },
  { label: "अंगोला", value: "Angola" },
  { label: "एंटीगुआ और बारबुडा", value: "Antigua and Barbuda" },
  { label: "अर्जेंटीना", value: "Argentina" },
  { label: "आर्मेनिया", value: "Armenia" },
  { label: "ऑस्ट्रेलिया", value: "Australia" },
  { label: "ऑस्ट्रिया", value: "Austria" },
  { label: "अज़रबैजान", value: "Azerbaijan" },
  { label: "बहामास", value: "Bahamas" },
  { label: "बहरीन", value: "Bahrain" },
  { label: "बांग्लादेश", value: "Bangladesh" },
  { label: "बारबाडोस", value: "Barbados" },
  { label: "बेलारूस", value: "Belarus" },
  { label: "बेल्जियम", value: "Belgium" },
  { label: "बेलीज", value: "Belize" },
  { label: "बेनिन", value: "Benin" },
  { label: "भूटान", value: "Bhutan" },
  { label: "बोलीविया", value: "Bolivia" },
  { label: "बोस्निया और हर्जेगोविना", value: "Bosnia and Herzegovina" },
  { label: "बोत्सवाना", value: "Botswana" },
  { label: "ब्राज़ील", value: "Brazil" },
  { label: "ब्रुनेई", value: "Brunei Darussalam" },
  { label: "बुल्गारिया", value: "Bulgaria" },
  { label: "बुर्किना फासो", value: "Burkina Faso" },
  { label: "बुरुंडी", value: "Burundi" },
  { label: "कंबोडिया", value: "Cambodia" },
  { label: "कैमरून", value: "Cameroon" },
  { label: "कनाडा", value: "Canada" },
  { label: "केप वर्डे", value: "Cabo Verde" },
  { label: "मध्य अफ्रीकी गणराज्य", value: "Central African Republic" },
  { label: "चाड", value: "Chad" },
  { label: "चिली", value: "Chile" },
  { label: "चीन", value: "China" },
  { label: "कोलंबिया", value: "Colombia" },
  { label: "कोमोरोस", value: "Comoros" },
  { label: "कांगो", value: "Congo" },
  { label: "कांगो (लोकतांत्रिक गणराज्य)", value: "Congo (Democratic Republic of)" },
  { label: "कोस्टा रिका", value: "Costa Rica" },
  { label: "कोटे डी आइवर", value: "Cote d'Ivoire" },
  { label: "क्रोएशिया", value: "Croatia" },
  { label: "क्यूबा", value: "Cuba" },
  { label: "साइप्रस", value: "Cyprus" },
  { label: "चेक गणराज्य", value: "Czech Republic" },
  { label: "डेनमार्क", value: "Denmark" },
  { label: "जिबूती", value: "Djibouti" },
  { label: "डोमिनिका", value: "Dominica" },
  { label: "डोमिनिकन गणराज्य", value: "Dominican Republic" },
  { label: "इक्वाडोर", value: "Ecuador" },
  { label: "मिस्र", value: "Egypt" },
  { label: "अल साल्वाडोर", value: "El Salvador" },
  { label: "भूमध्यरेखीय गिनी", value: "Equatorial Guinea" },
  { label: "इरिट्रिया", value: "Eritrea" },
  { label: "एस्टोनिया", value: "Estonia" },
  { label: "इथियोपिया", value: "Ethiopia" },
  { label: "फ़िजी", value: "Fiji" },
  { label: "फिनलैंड", value: "Finland" },
  { label: "फ्रांस", value: "France" },
  { label: "गैबॉन", value: "Gabon" },
  { label: "गाम्बिया", value: "Gambia" },
  { label: "जॉर्जिया", value: "Georgia" },
  { label: "जर्मनी", value: "Germany" },
  { label: "घाना", value: "Ghana" },
  { label: "ग्रीस", value: "Greece" },
  { label: "ग्रेनेडा", value: "Grenada" },
  { label: "ग्वाटेमाला", value: "Guatemala" },
  { label: "गिनी", value: "Guinea" },
  { label: "गिनी-बिसाऊ", value: "Guinea-Bissau" },
  { label: "गुयाना", value: "Guyana" },
  { label: "हैती", value: "Haiti" },
  { label: "होंडुरास", value: "Honduras" },
  { label: "हंगरी", value: "Hungary" },
  { label: "आइसलैंड", value: "Iceland" },
  { label: "भारत", value: "India" },
  { label: "इंडोनेशिया", value: "Indonesia" },
  { label: "ईरान", value: "Iran" },
  { label: "इराक", value: "Iraq" },
  { label: "आयरलैंड", value: "Ireland" },
  { label: "इज़राइल", value: "Israel" },
  { label: "इटली", value: "Italy" },
  { label: "जमैका", value: "Jamaica" },
  { label: "जापान", value: "Japan" },
  { label: "जॉर्डन", value: "Jordan" },
  { label: "कजाकिस्तान", value: "Kazakhstan" },
  { label: "केन्या", value: "Kenya" },
  { label: "किरिबाती", value: "Kiribati" },
  { label: "कुवैत", value: "Kuwait" },
  { label: "किर्गिज़स्तान", value: "Kyrgyzstan" },
  { label: "लाओस", value: "Lao People's Democratic Republic" },
  { label: "लातविया", value: "Latvia" },
  { label: "लेबनान", value: "Lebanon" },
  { label: "लेसोथो", value: "Lesotho" },
  { label: "लाइबेरिया", value: "Liberia" },
  { label: "लीबिया", value: "Libya" },
  { label: "लिकटेंस्टाइन", value: "Liechtenstein" },
  { label: "लिथुआनिया", value: "Lithuania" },
  { label: "लक्समबर्ग", value: "Luxembourg" },
  { label: "मेडागास्कर", value: "Madagascar" },
  { label: "मलावी", value: "Malawi" },
  { label: "मलेशिया", value: "Malaysia" },
  { label: "मालदीव", value: "Maldives" },
  { label: "माली", value: "Mali" },
  { label: "माल्टा", value: "Malta" },
  { label: "मार्शल द्वीप समूह", value: "Marshall Islands" },
  { label: "मॉरिटानिया", value: "Mauritania" },
  { label: "मॉरीशस", value: "Mauritius" },
  { label: "मेक्सिको", value: "Mexico" },
  { label: "माइक्रोनेशिया", value: "Micronesia" },
  { label: "मोल्दोवा", value: "Moldova" },
  { label: "मोनाको", value: "Monaco" },
  { label: "मंगोलिया", value: "Mongolia" },
  { label: "मोंटेनेग्रो", value: "Montenegro" },
  { label: "मोरक्को", value: "Morocco" },
  { label: "मोजाम्बिक", value: "Mozambique" },
  { label: "म्यांमार", value: "Myanmar" },
  { label: "नामीबिया", value: "Namibia" },
  { label: "नौरू", value: "Nauru" },
  { label: "नेपाल", value: "Nepal" },
  { label: "नीदरलैंड", value: "Netherlands" },
  { label: "न्यूजीलैंड", value: "New Zealand" },
  { label: "निकारागुआ", value: "Nicaragua" },
  { label: "नाइजर", value: "Niger" },
  { label: "नाइजीरिया", value: "Nigeria" },
  { label: "उत्तर कोरिया", value: "North Korea" },
  { label: "उत्तरी मैसेडोनिया", value: "North Macedonia" },
  { label: "नॉर्वे", value: "Norway" },
  { label: "ओमान", value: "Oman" },
  { label: "पाकिस्तान", value: "Pakistan" },
  { label: "पलाऊ", value: "Palau" },
  { label: "पनामा", value: "Panama" },
  { label: "पापुआ न्यू गिनी", value: "Papua New Guinea" },
  { label: "पैराग्वे", value: "Paraguay" },
  { label: "पेरू", value: "Peru" },
  { label: "फिलीपींस", value: "Philippines" },
  { label: "पोलैंड", value: "Poland" },
  { label: "पुर्तगाल", value: "Portugal" },
  { label: "कतर", value: "Qatar" },
  { label: "रोमानिया", value: "Romania" },
  { label: "रूस", value: "Russia" },
  { label: "रवांडा", value: "Rwanda" },
  { label: "सेंट किट्स एंड नेविस", value: "Saint Kitts and Nevis" },
  { label: "सेंट लूसिया", value: "Saint Lucia" },
  { label: "सेंट विंसेंट एंड द ग्रेनाडीन्स", value: "Saint Vincent and the Grenadines" },
  { label: "समोआ", value: "Samoa" },
  { label: "सैन मैरिनो", value: "San Marino" },
  { label: "साओ टोमे और प्रिंसिपे", value: "Sao Tome and Principe" },
  { label: "सऊदी अरब", value: "Saudi Arabia" },
  { label: "सेनेगल", value: "Senegal" },
  { label: "सर्बिया", value: "Serbia" },
  { label: "सेशेल्स", value: "Seychelles" },
  { label: "सिएरा लियोन", value: "Sierra Leone" },
  { label: "सिंगापुर", value: "Singapore" },
  { label: "स्लोवाकिया", value: "Slovakia" },
  { label: "स्लोवेनिया", value: "Slovenia" },
  { label: "सोलोमन द्वीप", value: "Solomon Islands" },
  { label: "सोमालिया", value: "Somalia" },
  { label: "दक्षिण अफ्रीका", value: "South Africa" },
  { label: "दक्षिण कोरिया", value: "South Korea" },
  { label: "दक्षिण सूडान", value: "South Sudan" },
  { label: "स्पेन", value: "Spain" },
  { label: "श्रीलंका", value: "Sri Lanka" },
  { label: "सूडान", value: "Sudan" },
  { label: "सूरीनाम", value: "Suriname" },
  { label: "स्वीडन", value: "Sweden" },
  { label: "स्विट्जरलैंड", value: "Switzerland" },
  { label: "सीरिया", value: "Syria" },
  { label: "ताजिकिस्तान", value: "Tajikistan" },
  { label: "तंजानिया", value: "Tanzania" },
  { label: "थाईलैंड", value: "Thailand" },
  { label: "तिमोर-लेस्ते", value: "Timor-Leste" },
  { label: "टोगो", value: "Togo" },
  { label: "टोंगा", value: "Tonga" },
  { label: "त्रिनिदाद और टोबैगो", value: "Trinidad and Tobago" },
  { label: "ट्यूनीशिया", value: "Tunisia" },
  { label: "तुर्की", value: "Turkey" },
  { label: "तुर्कमेनिस्तान", value: "Turkmenistan" },
  { label: "तुवालु", value: "Tuvalu" },
  { label: "युगांडा", value: "Uganda" },
  { label: "यूक्रेन", value: "Ukraine" },
  { label: "संयुक्त अरब अमीरात (UAE)", value: "UAE" },
  { label: "ब्रिटेन (UK)", value: "UK" },
  { label: "अमेरिका", value: "USA" },
  { label: "उरुग्वे", value: "Uruguay" },
  { label: "उज्बेकिस्तान", value: "Uzbekistan" },
  { label: "वानुअतु", value: "Vanuatu" },
  { label: "वेनेजुएला", value: "Venezuela" },
  { label: "वियतनाम", value: "Vietnam" },
  { label: "यमन", value: "Yemen" },
  { label: "जाम्बिया", value: "Zambia" },
  { label: "जिम्बाब्वे", value: "Zimbabwe" },
  { label: "अन्य", value: "Other" },
]

export const relationOptions = [
  { label: "स्वयं", value: "self" },
  { label: "पिता", value: "father" },
  { label: "माता", value: "mother" },
  { label: "पति", value: "husband" },
  { label: "पत्नी", value: "wife" },
  { label: "पुत्र", value: "son" },
  { label: "पुत्री", value: "daughter" },
  { label: "भाई", value: "brother" },
  { label: "बहन", value: "sister" },
  { label: "दादा", value: "grandfather" },
  { label: "दादी", value: "grandmother" },
  { label: "पोता", value: "grandson" },
  { label: "पोती", value: "granddaughter" },
  { label: "पुत्रवधू", value: "other" },
  { label: "अन्य", value: "putravadhu" },
]

export const educationLevels = [
  { label: "अशिक्षित", value: "illiterate" },
  { label: "प्राथमिक (1-5)", value: "primary" },
  { label: "उच्च प्राथमिक (6-8)", value: "middle" },
  { label: "माध्यमिक (9-10)", value: "high_school" },
  { label: "उच्च माध्यमिक (11-12)", value: "intermediate" },
  { label: "स्नातक", value: "graduate" },
  { label: "स्नातकोत्तर", value: "post_graduate" },
  { label: "डॉक्टरेट", value: "doctorate" },
  { label: "डिप्लोमा", value: "diploma" },
  { label: "अन्य", value: "other" },
]

export const bloodGroups = [
  { label: "A+", value: "A+" },
  { label: "A-", value: "A-" },
  { label: "B+", value: "B+" },
  { label: "B-", value: "B-" },
  { label: "AB+", value: "AB+" },
  { label: "AB-", value: "AB-" },
  { label: "O+", value: "O+" },
  { label: "O-", value: "O-" },
  { label: "अज्ञात", value: "unknown" },
]

export const maritalStatusOptions = [
  { label: "अविवाहित", value: "single" },
  { label: "विवाहित", value: "married" },
  { label: "विधवा/विधु", value: "widowed" },
  { label: "तलाकशुदा", value: "divorced" },
  { label: "अलग", value: "separated" },
]

export const houseTypes = [
  { label: "कच्चा मकान", value: "kutcha" },
  { label: "पक्का मकान", value: "pucca" },
  { label: "अर्ध-पक्का", value: "semi_pucca" },
  { label: "झुग्गी", value: "slum" },
  { label: "अपार्टमेंट", value: "apartment" },
]

export const houseOwnershipOptions = [
  { label: "स्वयं का", value: "owned" },
  { label: "किराए का", value: "rented" },
  { label: "सरकारी", value: "government" },
  { label: "अन्य", value: "other" },
  { label: "पिता का", value: "pita_ka" },
  { label: "माता का", value: "mata_ka" },
  { label: "पति का", value: "pati_ka" }
]

export const waterSources = [
  { label: "नल का पानी", value: "tap" },
  { label: "हैंडपंप", value: "handpump" },
  { label: "कुआं", value: "well" },
  { label: "बोरवेल", value: "borewell" },
  { label: "नदी/तालाब", value: "river_pond" },
  { label: "अन्य", value: "other" },
]

export const cookingFuels = [
  { label: "LPG", value: "lpg" },
  { label: "लकड़ी", value: "wood" },
  { label: "कोयला", value: "coal" },
  { label: "गोबर", value: "dung" },
  { label: "केरोसिन", value: "kerosene" },
  { label: "अन्य", value: "other" },
]

export const vehicleTypes = [
  { label: "कोई नहीं", value: "NONE" },
  { label: "साइकिल", value: "BICYCLE" },
  { label: "मोटरसाइकिल", value: "MOTORCYCLE" },
  { label: "कार", value: "CAR" },
  { label: "ट्रक", value: "TRUCK" },
  { label: "अन्य", value: "OTHER" },
]

export const welfareSchemeOptions = [
  { label: "प्रधानमंत्री आवास योजना", value: "pm_awas" },
  { label: "मनरेगा", value: "mgnrega" },
  { label: "राशन कार्ड", value: "ration_card" },
  { label: "आयुष्मान भारत", value: "ayushman_bharat" },
  { label: "किसान सम्मान निधि", value: "kisan_samman" },
  { label: "बेटी बचाओ बेटी पढ़ाओ", value: "beti_bachao" },
  { label: "अन्य", value: "other" },
]
