import type { FamilyMember } from "./types"

export const initialMember: FamilyMember = {
  id: "",
  firstName: "",
  lastName: "",
  dateOfBirth: "",
  age: 0,
  gender: "MALE",
  relation: "",
  maritalStatus: "",
  gotra: "",
  disability: false,
  bloodGroup: "",
  mobileNumber: "",
  email: "",
  permanentAddress: "",
  currentAddress: "",
  state: "",
  district: "",
  pincode: "",
  village: "",
  isCurrentAddressInIndia: true,
  currentCountry: "भारत",
  isStudent: false,
  educationLevel: "",
  classCompleted: "",
  currentClass: "",
  collegeCourse: "",
  institutionName: "",
  enrollmentStatus: "",
  schoolName: "",
  higherEducationType: "",
  currentEducationCity: "",
  currentEducationCountry: "",
  isHelpRequiredFromSamaj: false,
  isCurrentlyEnrolled: false,
  dropoutReason: "",
  educationMode: "",
  isStudyingAbroad: false,
  scholarshipReceived: false,
  scholarshipDetails: "",
  boardOrUniversity: "",
  yearOfPassing: undefined,
  fieldOfStudy: "",
  isEmployed: false,
  isSeekingJob: false,
  occupationType: "",
  employmentStatus: "",
  monthlyIncome: 0,
  incomeSourceCountry: false,
  incomeSourceCountryName: "",
  countryName: "",
  jobCategory: "",
  employerOrganizationName: "",
  isGovernmentJob: false,
  jobPosition: "",
  jobType: "",
  workExperienceYears: 0,
  isSelfEmployed: false,
  selfEmployedJobType: "",
  nameOfBusiness: "",
  businessCategory: "",
  businessType: "",
  customBusinessType: "",
  numberOfEmployees: 0,
  sizeOfBusiness: "",
  businessRegistration: false,
  isBusinessRegistered: false,
  willingToHirePeople: false,
  needsEmployees: false,
  occupationState: "",
  occupationCity: "",
  preferredJobLocation: "",
  preferredSector: "",
  isOpenToRelocate: false,
  workingHoursPerWeek: 0,
  hasAdditionalSkills: false,
  jobSearchSector: "",
  customJobSearchSector: "",
  wantsToGoAbroad: false,
  hasPassport: false,
  livestock: "",
  landOwned: 0,
  houseType: "",
  houseOwnership: "",
  hasElectricity: false,
  waterSource: "",
  hasToilet: false,
  cookingFuel: "",
  hasHealthIssues: false,
  chronicDisease: "",
  isVaccinated: false,
  hasHealthInsurance: false,
  isInterestedInFutureHealthPolicy: false,
  hasSmartphone: false,
  hasInternet: false,
  hasBankAccount: false,
  hasJanDhan: false,
  isMukhiya: false,
  welfareSchemes: [],
  isInterestedInFutureSamuhikVivah: false,
  vehicleType: "NONE",
}

export const statesAndDistricts: Record<string, string[]> = {
  "आंध्र प्रदेश": ["विशाखापत्तनम", "विजयवाड़ा", "गुंटूर", "नेल्लोर", "कुर्नूल", "राजमहेंद्रवरम", "तिरुपति", "अनंतपुर"],
  "अरुणाचल प्रदेश": ["ईटानगर", "नाहरलागुन", "पासीघाट", "अलोंग", "बोमडिला", "तेजू", "सेपा", "चांगलांग"],
  असम: ["गुवाहाटी", "सिलचर", "डिब्रूगढ़", "जोरहाट", "नगांव", "तिनसुकिया", "बोंगाईगांव", "धुबरी"],
  बिहार: ["पटना", "गया", "भागलपुर", "मुजफ्फरपुर", "दरभंगा", "बिहार शरीफ", "आरा", "पूर्णिया"],
  छत्तीसगढ़: ["रायपुर", "भिलाई", "बिलासपुर", "कोरबा", "दुर्ग", "राजनांदगांव", "रायगढ़", "जगदलपुर"],
  गोवा: ["पणजी", "वास्को दा गामा", "मडगांव", "पोंडा", "मापुसा", "बिचोलिम", "कैंडोलिम", "कलंगुट"],
  गुजरात: ["अहमदाबाद", "सूरत", "वडोदरा", "राजकोट", "भावनगर", "जामनगर", "जूनागढ़", "गांधीनगर"],
  हरियाणा: ["गुरुग्राम", "फरीदाबाद", "पानीपत", "अंबाला", "यमुनानगर", "रोहतक", "हिसार", "करनाल"],
  "हिमाचल प्रदेश": ["शिमला", "मंडी", "सोलन", "नाहन", "हमीरपुर", "उना", "कुल्लू", "धर्मशाला"],
  झारखंड: ["रांची", "जमशेदपुर", "धनबाद", "बोकारो", "देवघर", "हजारीबाग", "गिरिडीह", "रामगढ़"],
  कर्नाटक: ["बेंगलुरु", "मैसूर", "हुबली", "मंगलुरु", "बेलगावी", "दावणगेरे", "बल्लारी", "तुमकुर"],
  केरल: ["तिरुवनंतपुरम", "कोच्चि", "कोझिकोड", "त्रिशूर", "कन्नूर", "कोल्लम", "पलक्कड़", "अलप्पुझा"],
  "मध्य प्रदेश": ["भोपाल", "इंदौर", "ग्वालियर", "जबलपुर", "उज्जैन", "सागर", "देवास", "सतना"],
  महाराष्ट्र: ["मुंबई", "पुणे", "नाशिक", "नागपुर", "औरंगाबाद", "सोलापुर", "अमरावती", "कोल्हापुर"],
  मणिपुर: ["इंफाल", "तौबल", "बिष्णुपुर", "चुराचांदपुर", "उखरुल", "सेनापति", "तमेंगलोंग", "कांगपोकपी"],
  मेघालय: ["शिलांग", "तुरा", "जोवाई", "नोंगस्टोइन", "बागमारा", "विलियमनगर", "रीभोई", "खलीहरिंग"],
  मिजोरम: ["आइजोल", "लुंगलेई", "चंफाई", "कोलासिब", "सेरछिप", "लावंगतलाई", "सैहा", "मामित"],
  नगालैंड: ["कोहिमा", "दीमापुर", "मोकोकचुंग", "तुएनसांग", "वोखा", "जुन्हेबोटो", "फेक", "लोंगलेंग"],
  ओडिशा: ["भुवनेश्वर", "कटक", "राउरकेला", "ब्रह्मपुर", "संबलपुर", "पुरी", "बालासोर", "बारगढ़"],
  पंजाब: ["चंडीगढ़", "लुधियाना", "अमृतसर", "जालंधर", "पटियाला", "बठिंडा", "मोहाली", "फिरोजपुर"],
  राजस्थान: ["जयपुर", "जोधपुर", "उदयपुर", "कोटा", "अजमेर", "बीकानेर", "भरतपुर", "अलवर"],
  सिक्किम: ["गंगटोक", "नामची", "ग्यालसिंग", "मंगन", "जोरेथांग", "सिंगतम", "रंगपो", "पेलिंग"],
  तमिलनाडु: ["चेन्नई", "कोयम्बटूर", "मदुरै", "सालेम", "तिरुचिरापल्ली", "तिरुनेलवेली", "वेल्लोर", "इरोड"],
  तेलंगाना: ["हैदराबाद", "वारंगल", "निजामाबाद", "खम्मम", "करीमनगर", "रामगुंडम", "महबूबनगर", "नालगोंडा"],
  त्रिपुरा: ["अगरतला", "धर्मनगर", "उदयपुर", "कैलाशहर", "बेलोनिया", "खोवाई", "अंबासा", "सब्रूम"],
  "उत्तर प्रदेश": ["लखनऊ", "कानपुर", "आगरा", "वाराणसी", "मेरठ", "इलाहाबाद", "बरेली", "अलीगढ़"],
  उत्तराखंड: ["देहरादून", "हरिद्वार", "रुड़की", "हल्द्वानी", "रामनगर", "काशीपुर", "रोहतक", "पिथौरागढ़"],
  "पश्चिम बंगाल": ["कोलकाता", "हावड़ा", "दुर्गापुर", "आसनसोल", "सिलीगुड़ी", "बर्धमान", "मालदा", "कूच बिहार"],
}

export const occupationTypes = [
  { label: "किसान", value: "farmer" },
  { label: "मजदूर", value: "laborer" },
  { label: "निजी नौकरी", value: "private_job" },
  { label: "सरकारी नौकरी", value: "government_job" },
  { label: "स्व-रोजगार", value: "self_employed" },
  { label: "व्यापार", value: "business" },
  { label: "पेशेवर (डॉक्टर, वकील आदि)", value: "professional" },
  { label: "फ्रीलांसर", value: "freelancer" },
  { label: "स्टार्टअप संस्थापक", value: "startup_founder" },
  { label: "घरेलू सहायक / कामकाजी महिला", value: "domestic_worker" },
  { label: "गृहिणी", value: "housewife" },
  { label: "सेवानिवृत्त", value: "retired" },
  { label: "गिग वर्कर (Zomato, Uber आदि)", value: "gig_worker" },
  { label: "प्रशिक्षु / इंटर्न", value: "intern" },
  { label: "विक्रेता / दुकानदार", value: "vendor" },
  { label: "दस्तकारी / शिल्पकार", value: "artisan" },
  { label: "अन्य", value: "other" },
]

export const jobTypes = [
  { label: "इंजीनियर", value: "engineer" },
  { label: "डॉक्टर", value: "doctor" },
  { label: "मेडिकल वर्कर", value: "medical_worker" },
  { label: "आईटी प्रोफेशनल", value: "it_professional" },
  { label: "शिक्षक", value: "teacher" },
  { label: "वकील", value: "lawyer" },
  { label: "प्रशासनिक अधिकारी", value: "administrative_officer" },
  { label: "अकाउंटेंट", value: "accountant" },
  { label: "बैंकिंग", value: "banking" },
  { label: "सेल्स & मार्केटिंग", value: "sales_marketing" },
  { label: "HR", value: "hr" },
  { label: "अन्य", value: "other" },
]

export const businessTypes = [
  { label: "MSME", value: "msme" },
  { label: "प्राइवेट लिमिटेड", value: "private_ltd" },
  { label: "प्रोप्राइटरशिप", value: "proprietorship" },
  { label: "पार्टनरशिप", value: "partnership" },
  { label: "शॉप/दुकान", value: "shop" },
  { label: "ऑनलाइन बिजनेस", value: "online_business" },
  { label: "अन्य", value: "other" },
]

export const countries = [
  { label: "संयुक्त अरब अमीरात (UAE)", value: "UAE" },
  { label: "सऊदी अरब", value: "Saudi Arabia" },
  { label: "कतर", value: "Qatar" },
  { label: "कुवैत", value: "Kuwait" },
  { label: "ओमान", value: "Oman" },
  { label: "बहरीन", value: "Bahrain" },
  { label: "अमेरिका", value: "USA" },
  { label: "कनाडा", value: "Canada" },
  { label: "ऑस्ट्रेलिया", value: "Australia" },
  { label: "ब्रिटेन (UK)", value: "UK" },
  { label: "सिंगापुर", value: "Singapore" },
  { label: "जर्मनी", value: "Germany" },
  { label: "न्यूजीलैंड", value: "New Zealand" },
  { label: "अन्य", value: "Other" },
]

export const relationOptions = [
  { label: "पिता", value: "father" },
  { label: "माता", value: "mother" },
  { label: "पति", value: "husband" },
  { label: "पत्नी", value: "wife" },
  { label: "पुत्र", value: "son" },
  { label: "पुत्री", value: "daughter" },
  { label: "भाई", value: "brother" },
  { label: "बहन", value: "sister" },
  { label: "दादा", value: "grandfather" },
  { label: "दादी", value: "grandmother" },
  { label: "पोता", value: "grandson" },
  { label: "पोती", value: "granddaughter" },
  { label: "अन्य", value: "other" },
]

export const educationLevels = [
  { label: "अशिक्षित", value: "illiterate" },
  { label: "प्राथमिक (1-5)", value: "primary" },
  { label: "माध्यमिक (6-8)", value: "middle" },
  { label: "हाई स्कूल (9-10)", value: "high_school" },
  { label: "इंटरमीडिएट (11-12)", value: "intermediate" },
  { label: "स्नातक", value: "graduate" },
  { label: "स्नातकोत्तर", value: "post_graduate" },
  { label: "डॉक्टरेट", value: "doctorate" },
  { label: "डिप्लोमा", value: "diploma" },
  { label: "अन्य", value: "other" },
]

export const bloodGroups = [
  { label: "A+", value: "A+" },
  { label: "A-", value: "A-" },
  { label: "B+", value: "B+" },
  { label: "B-", value: "B-" },
  { label: "AB+", value: "AB+" },
  { label: "AB-", value: "AB-" },
  { label: "O+", value: "O+" },
  { label: "O-", value: "O-" },
  { label: "अज्ञात", value: "unknown" },
]

export const maritalStatusOptions = [
  { label: "अविवाहित", value: "single" },
  { label: "विवाहित", value: "married" },
  { label: "विधवा/विधुर", value: "widowed" },
  { label: "तलाकशुदा", value: "divorced" },
  { label: "अलग", value: "separated" },
]

export const houseTypes = [
  { label: "कच्चा मकान", value: "kutcha" },
  { label: "पक्का मकान", value: "pucca" },
  { label: "अर्ध-पक्का", value: "semi_pucca" },
  { label: "झुग्गी", value: "slum" },
  { label: "अपार्टमेंट", value: "apartment" },
]

export const houseOwnershipOptions = [
  { label: "स्वयं का", value: "owned" },
  { label: "किराए का", value: "rented" },
  { label: "सरकारी", value: "government" },
  { label: "अन्य", value: "other" },
]

export const waterSources = [
  { label: "नल का पानी", value: "tap" },
  { label: "हैंडपंप", value: "handpump" },
  { label: "कुआं", value: "well" },
  { label: "बोरवेल", value: "borewell" },
  { label: "नदी/तालाब", value: "river_pond" },
  { label: "अन्य", value: "other" },
]

export const cookingFuels = [
  { label: "LPG", value: "lpg" },
  { label: "लकड़ी", value: "wood" },
  { label: "कोयला", value: "coal" },
  { label: "गोबर", value: "dung" },
  { label: "केरोसिन", value: "kerosene" },
  { label: "अन्य", value: "other" },
]

export const vehicleTypes = [
  { label: "कोई नहीं", value: "NONE" },
  { label: "साइकिल", value: "BICYCLE" },
  { label: "मोटरसाइकिल", value: "MOTORCYCLE" },
  { label: "कार", value: "CAR" },
  { label: "ट्रक", value: "TRUCK" },
  { label: "अन्य", value: "OTHER" },
]

export const welfareSchemeOptions = [
  { label: "प्रधानमंत्री आवास योजना", value: "pm_awas" },
  { label: "मनरेगा", value: "mgnrega" },
  { label: "राशन कार्ड", value: "ration_card" },
  { label: "आयुष्मान भारत", value: "ayushman_bharat" },
  { label: "किसान सम्मान निधि", value: "kisan_samman" },
  { label: "बेटी बचाओ बेटी पढ़ाओ", value: "beti_bachao" },
  { label: "अन्य", value: "other" },
]
