export const USER_ROLES = {
  SUPERADMIN: "superadmin",
  CHOKHLA: "chokhla",
  VILLAGE_ADMIN: "village_admin",
} as const

export const USER_STATUS = {
  ACTIVE: "active",
  INACTIVE: "inactive",
  PENDING: "pending",
} as const

export const VILLAGE_STATUS = {
  ACTIVE: "active",
  INACTIVE: "inactive",
} as const

export const CHOKHLA_STATUS = {
  ACTIVE: "active",
  INACTIVE: "inactive",
  PENDING: "pending",
} as const

export const SIDEBAR_ITEMS = [
  {
    id: "dashboard",
    label: "डैशबोर्ड",
    icon: "LayoutDashboard",
  },
  {
    id: "users",
    label: "उपयोगकर्ता प्रबंधन",
    icon: "Users",
  },
  {
    id: "villages",
    label: "गांव प्रबंधन",
    icon: "MapPin",
  },
  {
    id: "chokhlas",
    label: "चोखला प्रबंधन",
    icon: "Building2",
  },
  {
    id: "statistics",
    label: "आंकड़े और रिपोर्ट",
    icon: "BarChart3",
  },
  {
    id: "profile",
    label: "प्रोफाइल सेटिंग्स",
    icon: "Settings",
  },
] as const

export const INDIAN_STATES = [
  "आंध्र प्रदेश",
  "अरुणाचल प्रदेश",
  "असम",
  "बिहार",
  "छत्तीसगढ़",
  "गोवा",
  "गुजरात",
  "हरियाणा",
  "हिमाचल प्रदेश",
  "झारखंड",
  "कर्नाटक",
  "केरल",
  "मध्य प्रदेश",
  "महाराष्ट्र",
  "मणिपुर",
  "मेघालय",
  "मिजोरम",
  "नागालैंड",
  "ओडिशा",
  "पंजाब",
  "राजस्थान",
  "सिक्किम",
  "तमिलनाडु",
  "तेलंगाना",
  "त्रिपुरा",
  "उत्तर प्रदेश",
  "उत्तराखंड",
  "पश्चिम बंगाल",
] as const

export const STATES_DISTRICTS: Record<string, string[]> = {
  गुजरात: [
    "अहमदाबाद",
    "अमरेली",
    "आनंद",
    "अरावली",
    "बनासकांठा",
    "भरूच",
    "भावनगर",
    "बोटाद",
    "छोटा उदयपुर",
    "दाहोद",
    "दांग",
    "देवभूमि द्वारका",
    "गांधीनगर",
    "गिर सोमनाथ",
    "जामनगर",
    "जूनागढ़",
    "कच्छ",
    "खेड़ा",
    "महिसागर",
    "मेहसाणा",
    "मोरबी",
    "नर्मदा",
    "नवसारी",
    "पंचमहल",
    "पाटन",
    "पोरबंदर",
    "राजकोट",
    "साबरकांठा",
    "सूरत",
    "सुरेंद्रनगर",
    "तापी",
    "वडोदरा",
    "वलसाड",
  ],
  राजस्थान: [
    "अजमेर",
    "अलवर",
    "बांसवाड़ा",
    "बारां",
    "बाड़मेर",
    "भरतपुर",
    "भीलवाड़ा",
    "बीकानेर",
    "बूंदी",
    "चित्तौड़गढ़",
    "चूरू",
    "दौसा",
    "धौलपुर",
    "डूंगरपुर",
    "हनुमानगढ़",
    "जयपुर",
    "जैसलमेर",
    "जालौर",
    "झालावाड़",
    "झुंझुनू",
    "जोधपुर",
    "करौली",
    "कोटा",
    "नागौर",
    "पाली",
    "प्रतापगढ़",
    "राजसमंद",
    "सवाई माधोपुर",
    "सीकर",
    "सिरोही",
    "श्रीगंगानगर",
    "टोंक",
    "उदयपुर",
  ],
}

export const MOCK_STATISTICS = {
  totalUsers: 1247,
  totalVillages: 156,
  totalChokhlas: 23,
  totalPopulation: 89432,
  activeUsers: 1198,
  pendingUsers: 49,
  recentRegistrations: 34,
  monthlyGrowth: 12.5,
}
